name: Test Building Image

on:
  pull_request:

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ilyes512/ansiblek8t
          push: false
